<?php
$keyfile="key.inc.php";
if(!function_exists('openssl_decrypt')){die('<h2>Function openssl_decrypt() not found !</h2>');}
if(!defined('_FILE_')){define("_FILE_",getcwd().DIRECTORY_SEPARATOR.basename($_SERVER['PHP_SELF']),false);}
if(!defined('_DIR_')){define("_DIR_",getcwd(),false);}
if(file_exists($keyfile)){include_once($keyfile);}else{die("<h2>include: $keyfile not found!</h2>");}
$e7091="ZkZ5T0VGR0IvS1A2TDh1YkNVZms2RUgrQ0JJVE4ydzFDR00wazJqdi9jeWZ4WjJWYkNuRFY5UVZEN3dCNEg3Wmo5bkxnWDAvc3R2dmIzOGFPMXBQNWhSaTdyYWIrT0lNSk5Yb2JWaVJHdnB6UzNMZzJKMXMxTnlPck1kTVZRL2dRazFmNDNFaytWUTZhMnNnUmlGSEZRc0lWekJMdmF4dFRMblM4U0ZIZXQzZTg2Q0NrdDl2RkVsVlVnZkxmYkJsZkRKMDNEV3N2dHBLTm5CMGxaVEt3WU1meXgxTnFsS2Rkdmo3KzZnZnQ1T2ZtYUVNRHc0Rm10NWo1TjhyWlFDRlJjdnBGNDRCTllzenR2OGc0Uml4KzQxN25wV1VNRTVGODhIcGVPNytZdzNDK0xMTTEyZmlpYlpBNnA5dGlacXRhVjlZS0NMR2RzcDJWTDNuMDdRS3FiUmhLSkM1ZTJIRTNFdGhoQTZOYUtacVc4aUhtNXNWUFpZcnhPaitkbHRXeks5eElxYUp5eHJkcGRVejhLRGtaVGx5L002by9wTjUxNmxmK0dCc2FkUnlINE9yYkhCMHZINXJhMXZkbDUvd1Z2UEZCTHNKVi93RVMxeEI3cm5zRGZ5MEU1UmNiUVFRSU0vZmFjVDFlTkxYMytTQlJYYXBtL2pzRm5QZ2ptL2k0SzlLTm9YV2lEYnc1R1JHVHRUb1kvVkpiRHloSnlQVVo2OXllUTdmYmh6SVdRRzNnUllYK1FkYWl6Z1c2a08wakw2NUNCWnZpR2ttZWpzT0dyQVhJUW1wNTJFUHdEQVhGeXg5Q1pQNGIwMHNvUENQZWQxSk5xdFdvSDMwTHM1REhTK0RZbkcyVG1RVGdlY3EybmIya1liQkJNVTFHSXF3eFFHRW95YXV4cGFoZCsxR3hYN0h5RDhVZlpybkNCS0Y=";eval(e7061($e7091));
?>
